#SPDX-License-Identifier: MIT-0
---
# tasks file for build_images
- name: Genera la coppia di chiavi SSH 
  community.crypto.openssh_keypair:
    path: "{{ playbook_dir }}/Dockerfiles/id_rsa"
    type: rsa
    state: present
  register: ssh_key_result

- name: Leggo contenuto della chiave
  ansible.builtin.slurp:
    src: "{{ playbook_dir }}/Dockerfiles/id_rsa.pub"
  register: pub_key_encoded

- name: Imposto la variabile con il testo della chiave pubblica
  ansible.builtin.set_fact:
    pub_key_content: "{{ pub_key_encoded.content | b64decode }}"

# ------------------ UBUNTU 22.04 ------------------
- name: Build immagine Ubuntu 22.04
  community.docker.docker_image:
    name: "{{ image_name_a }}"
    build:
      path: ./Dockerfiles
      dockerfile: "{{ dockerfile_a }}"
      args:
        SSH_PUBLIC_KEY: "{{ pub_key_content }}"
      pull: true
    source: build

- name: Avvio container Ubuntu (Porta 2221)
  community.docker.docker_container:
    name: "{{ container_name_a }}"
    image: "{{ image_name_a }}"
    state: started
    restart_policy: always
    ports:
      - "{{ ports_a }}"

# ------------------ ROCKY LINUX 9 ------------------
- name: Build immagine Rocky Linux 9
  community.docker.docker_image:
    name: "{{ image_name_b }}"
    build:
      path: ./Dockerfiles
      dockerfile: "{{ dockerfile_b }}"
      args:
        SSH_PUBLIC_KEY: "{{ pub_key_content }}"
      pull: true
    source: build

- name: Avvio container Rocky Linux (Porta 2222)
  community.docker.docker_container:
    name: "{{ container_name_b }}"
    image: "{{ image_name_b }}"
    state: started
    restart_policy: always
    ports:
      - "{{ ports_b }}"
