#SPDX-License-Identifier: MIT-0
---
# defaults file for build_images
image_name_a: ubuntu-ssh-node
image_name_b: rocky-ssh-node

container_name_a: node-ubuntu
container_name_b: node-rocky

dockerfile_a: Dockerfile.ubuntu
dockerfile_b: Dockerfile.rocky

ports_a: "2221:22"

ports_b: "2222:22"